export const enum Instruction {
  INSTRUCTION_HALT,
  INSTRUCTION_PUSH,
  INSTRUCTION_LOG,
  INSTRUCTION_ADD,
  INSTRUCTION_LOAD,
  INSTRUCTION_INC,
  INSTRUCTION_JMP,
  INSTRUCTION_JLE,
  INSTRUCTION_JL,
  INSTRUCTION_LABEL,
  INSTRUCTION_NOP,
}


export const test = 23;
